# Generated by Django 5.0 on 2024-01-03 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LittleLemonAPI", "0002_alter_menuitem_unique_together_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="LittleLemonAPI.cart",
            ),
        ),
    ]
